name: Build VyOS LTS

# on: 
#   release:
#     types: [published]
#   push:
#     branches: 
#       - master
# on:
#   push:
#     tags:
#       - 'v*'
on:
  workflow_dispatch  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

    - name: Pull vyos-build docker image
      run: |
        docker pull vyos/vyos-build:equuleus
        
    - name: Build iso
      run: |
        git clone -b equuleus --single-branch https://github.com/vyos/vyos-build.git
        cd vyos-build
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:equuleus bash -c './configure --architecture amd64 --build-type release --version "${{ github.event.inputs.version}}" && sudo make iso'

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"  

    - name: Release snapshot
      id: release-snapshot
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.myToken }}
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.myToken }}
        file: vyos-build/build/vyos-${{ steps.date.outputs.date }}-amd64.iso
        tag: ${{ steps.date.outputs.date }}
        overwrite: true
        file_glob: true
  
  
