name: Build VyOS LTS

# on: 
#   release:
#     types: [published]
#   push:
#     branches: 
#       - master
# on:
#   push:
#     tags:
#       - 'v*'
on:
  workflow_dispatch  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1.1.0
      with:
        format: "YYYYMMDDHHmmss"

    - name: Output1
      run: |
        echo "The time was ${{ steps.t1.outputs.time }}"
        echo "The year was ${{ steps.t1.outputs.year }}"
        echo "The month was ${{ steps.t1.outputs.month }}"
        echo "The day was ${{ steps.t1.outputs.day }}"
        echo "The hours was ${{ steps.t1.outputs.hours }}"
        echo "The minutes was ${{ steps.t1.outputs.minutes }}"
        echo "The seconds was ${{ steps.t1.outputs.seconds }}"
        echo "The milliseconds was ${{ steps.t1.outputs.milliseconds }}"
        echo "The day_of_week was ${{ steps.t1.outputs.day_of_week }}"
        echo "The week_of_year was ${{ steps.t1.outputs.week_of_year }}"
        echo "The milliseconds_since_epoch was ${{ steps.t1.outputs.milliseconds_since_epoch }}"

    - name: Pull vyos-build docker image
      run: |
        docker pull vyos/vyos-build:equuleus
        
    - name: Build iso
      run: |
        git clone -b equuleus --single-branch https://github.com/vyos/vyos-build.git
        cd vyos-build
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:equuleus bash -c './configure --architecture amd64 --build-type release --version "${{ steps.date.outputs.date }}" && sudo make iso'


    - name: Release snapshot
      id: release-snapshot
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.myToken }}
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.myToken }}
        file: vyos-build/build/vyos-${{ steps.date.outputs.date }}-amd64.iso
        tag: ${{ steps.date.outputs.date }}
        overwrite: true
        file_glob: true
  
  
